### ISSUE TITLE
[Feature] Consider trasparent backgrounds

### ISSUE THREAD

**Issue by cinghiopinghio** [dsummersl/nvim-sluice#1]
Hi, cool project.

In my colorscheme, `Normal` background is transparent: `guibg=none`.
When I try to use your plugin, `nvim` complains that it cannot find `guibg` in the following line:
https://github.com/dsummersl/nvim-sluice/blob/88179d4d932c73731a68c33c6829d600d4017148/lua/sluice.lua#L111

**Comment by dsummersl** [comment]
Thanks for the report I'll look into it more today - tried it myself by setting:

```
hi Normal guibg=none
hi SignColumn guibg=none
```

and couldn't reproduce it - maybe its an nvim version thing? My version is NVIM v0.5.0-7e0e078 -- how about you?

**Comment by cinghiopinghio** [comment]
That's strange.

The version of my `nvim` is `v0.5.0-899-gfa73bb70f` (built today).

In particular the messages are as follows:

```
Error detected while processing CursorMoved Autocommands for "*":
E5108: Error executing lua /home/mauro/.config/nvim/bundle/nvim-sluice/lua/sluice.lua:111: Vim(highlight):E417: missing argument: guibg=
```

Although I also get when opening a given file:

```
Error detected while processing CursorMoved Autocommands for "*":
E5108: Error executing lua /home/mauro/.config/nvim/bundle/nvim-sluice/lua/sluice.lua:70: 'width' key must be a positive Integer
```

**Comment by avonmoll** [comment]
I do not receive the error OP mentioned, but the nvim-sluice column(s) on the right side of the window are opaque even though I have 

```
hi Normal guibg=none
hi SignColumn guibg=none
```

I'm using NVIM v0.5.0-904-g0c8d6ab53.

**Side note**: the nvim-sluice columns are always 1-2 columns away from being all the way to the right, and the width seems to be variable (sometimes 2 columns wide, sometimes 3). If it matters, I'm using iTerm2 on macos.

**Comment by dsummersl** [comment]
Hi there all, thank you so much for the feedback - I'm going to hack at this some more over the weekend. @cinghiopinghio I updated to the latest head version of neovim yesterday, and still couldn't reproduce the issues. Not sure how to reproduce, but I'll give it another go !

@avonmoll I think the background of the window I'm presenting the gutter in is itself 'opaque' by default ... hopefully I can just change its default color. Keep you posted!

**Comment by cinghiopinghio** [comment]
I can confirm that this issue is linked my colorscheme that you can find [here](https://github.com/cinghiopinghio/futon.vim).
Both with transparent or opaque background `let g:futon_transp_bg=0` or `1` I receive those errors (that from line 111).

Using another colorscheme (namely `molokai`) no errors are raised.

**Comment by cinghiopinghio** [comment]
Ok, I spent a few minutes looking for the offending bit.

It seems that setting `hi SignColumn guibg=NONE` will trigger the error (note the full upper case, as in the docs).
if set as `hi SignColumn guibg=none` won't raise any issue although it's not acceptable in `vim` as transparent and the colorscheme won't be portable.

As a final note, the definition of `Normal` (either opaque or `none` or `NONE`) do not raise the error.

**Comment by dsummersl** [comment]
@cinghiopinghio & @avonmoll updated this project with a fix for the bg color issue, and added an optimization (throttling to ensure cursorhold type events don't bog down the editor).

**Comment by dsummersl** [comment]
Looking into the column-width issue @avonmoll next...currently the width is determined by the sign columns' width. Any pointers for when you see the width change?

**Comment by cinghiopinghio** [comment]
I confirm that the `guibg` issue is now solved. Thanks.

**Comment by avonmoll** [comment]
![image](https://user-images.githubusercontent.com/4260850/101363805-cf936200-386f-11eb-8439-b781c062bef3.png)

Thanks for looking into these issues! Above is a screenshot which shows the width of the sluice column and how it is not quite right-aligned. I noticed, while moving around my ~/.vimrc, that when the cursor goes to an indented line, the sluice column changes as shown:
![image](https://user-images.githubusercontent.com/4260850/101364077-2ac55480-3870-11eb-856e-6d9826847d27.png)

Otherwise, it seems like the column width is consistent when I open splits or change the window size now.

**Comment by dsummersl** [comment]
@avonmoll Updated the column to be explicitly 2 for the time being (I'd like to support the `signcolumn` setting, but that'd be more work!)

**Comment by avonmoll** [comment]
Thanks - definitely fixes the column width and placement for me. Now, if I hold down <kbd>j</kbd> for a while, neovim crashes with the error:

`Assertion failed: (((IRType)((ir->t).irt & IRT_TYPE)) != st), function asm_conv, file ./lj_asm_x86.h, line 813.`

---
_Edit_: to be sure, I tested with and without nvim-sluice installed and it happened consistently only in the former.

**Comment by dsummersl** [comment]
hmm, a lua problem :(

https://github.com/LuaJIT/LuaJIT/blob/v2.1.0-beta3/src/lj_asm_x86.h#L813

Maybe this...somewhere around here.

I'll see if I can reproduce.

**Comment by cinghiopinghio** [comment]
The original issue is solved. @dsummersl : Feel free to close it.
