### ISSUE TITLE
Blocking error when setting attributes

### ISSUE THREAD

**Issue by cinghiopinghio** [dsummersl/nvim-sluice#2]
Hi,

I still have an issue with `sluice`.
I get the following error (with several colorschemes):

```
Error detected while processing CursorMoved Autocommands for "*":
E5108: Error executing lua /home/xxxx/.config/nvim/bundle/nvim-sluice/lua/sluice.lua:149: Vim(highlight):E423: Illegal argument: gui bold=1
```
It's fired after few moments in the file and it's a blocking error (nvim becomes unusable).

It seems to comes from the fact that colors are set as `guibg=#ffffff` while other attributes are set as `gui=attribute`.

**Comment by dsummersl** [comment]
I've pushed up a fix for this problem - please let me know if it addresses your issue!

**Comment by cinghiopinghio** [comment]
Wow, now it works like a charm!!! Thanks
